name: release-publish
run-name: changesets flow for npm packages 📦

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/release-publish.yml
      - .changeset/**/*
      - packages/**/*

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release-publish-job:
    name: Release Publish Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Lint and test
        run: npm run lint:packages

      - name: Build
        run: npm run build:packages

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
